"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
LICENSE: GNU General Public License v3.0 to Beem Development (https://github.com/beemdevelopment)
From https://github.com/beemdevelopment/Aegis/pull/406/files#diff-410b85c0f939a198f70af5fc855a21ed
Changes: modified package name.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MigrationPayload(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Algorithm:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _AlgorithmEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[MigrationPayload._Algorithm.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ALGORITHM_UNSPECIFIED: MigrationPayload._Algorithm.ValueType  # 0
        SHA1: MigrationPayload._Algorithm.ValueType  # 1
        SHA256: MigrationPayload._Algorithm.ValueType  # 2
        SHA512: MigrationPayload._Algorithm.ValueType  # 3
        MD5: MigrationPayload._Algorithm.ValueType  # 4

    class Algorithm(_Algorithm, metaclass=_AlgorithmEnumTypeWrapper): ...
    ALGORITHM_UNSPECIFIED: MigrationPayload.Algorithm.ValueType  # 0
    SHA1: MigrationPayload.Algorithm.ValueType  # 1
    SHA256: MigrationPayload.Algorithm.ValueType  # 2
    SHA512: MigrationPayload.Algorithm.ValueType  # 3
    MD5: MigrationPayload.Algorithm.ValueType  # 4

    class _DigitCount:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _DigitCountEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[MigrationPayload._DigitCount.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        DIGIT_COUNT_UNSPECIFIED: MigrationPayload._DigitCount.ValueType  # 0
        SIX: MigrationPayload._DigitCount.ValueType  # 1
        EIGHT: MigrationPayload._DigitCount.ValueType  # 2
        SEVEN: MigrationPayload._DigitCount.ValueType  # 3

    class DigitCount(_DigitCount, metaclass=_DigitCountEnumTypeWrapper): ...
    DIGIT_COUNT_UNSPECIFIED: MigrationPayload.DigitCount.ValueType  # 0
    SIX: MigrationPayload.DigitCount.ValueType  # 1
    EIGHT: MigrationPayload.DigitCount.ValueType  # 2
    SEVEN: MigrationPayload.DigitCount.ValueType  # 3

    class _OtpType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _OtpTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[MigrationPayload._OtpType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        OTP_TYPE_UNSPECIFIED: MigrationPayload._OtpType.ValueType  # 0
        HOTP: MigrationPayload._OtpType.ValueType  # 1
        TOTP: MigrationPayload._OtpType.ValueType  # 2

    class OtpType(_OtpType, metaclass=_OtpTypeEnumTypeWrapper): ...
    OTP_TYPE_UNSPECIFIED: MigrationPayload.OtpType.ValueType  # 0
    HOTP: MigrationPayload.OtpType.ValueType  # 1
    TOTP: MigrationPayload.OtpType.ValueType  # 2

    @_typing.final
    class OtpParameters(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SECRET_FIELD_NUMBER: _builtins.int
        NAME_FIELD_NUMBER: _builtins.int
        ISSUER_FIELD_NUMBER: _builtins.int
        ALGORITHM_FIELD_NUMBER: _builtins.int
        DIGITS_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        COUNTER_FIELD_NUMBER: _builtins.int
        UNIQUE_ID_FIELD_NUMBER: _builtins.int
        secret: _builtins.bytes
        name: _builtins.str
        issuer: _builtins.str
        algorithm: Global___MigrationPayload.Algorithm.ValueType
        digits: Global___MigrationPayload.DigitCount.ValueType
        type: Global___MigrationPayload.OtpType.ValueType
        counter: _builtins.int
        unique_id: _builtins.str
        def __init__(
            self,
            *,
            secret: _builtins.bytes = ...,
            name: _builtins.str = ...,
            issuer: _builtins.str = ...,
            algorithm: Global___MigrationPayload.Algorithm.ValueType = ...,
            digits: Global___MigrationPayload.DigitCount.ValueType = ...,
            type: Global___MigrationPayload.OtpType.ValueType = ...,
            counter: _builtins.int = ...,
            unique_id: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["algorithm", b"algorithm", "counter", b"counter", "digits", b"digits", "issuer", b"issuer", "name", b"name", "secret", b"secret", "type", b"type", "unique_id", b"unique_id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    OTP_PARAMETERS_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    BATCH_SIZE_FIELD_NUMBER: _builtins.int
    BATCH_INDEX_FIELD_NUMBER: _builtins.int
    BATCH_ID_FIELD_NUMBER: _builtins.int
    version: _builtins.int
    batch_size: _builtins.int
    batch_index: _builtins.int
    batch_id: _builtins.int
    @_builtins.property
    def otp_parameters(self) -> _containers.RepeatedCompositeFieldContainer[Global___MigrationPayload.OtpParameters]: ...
    def __init__(
        self,
        *,
        otp_parameters: _abc.Iterable[Global___MigrationPayload.OtpParameters] | None = ...,
        version: _builtins.int = ...,
        batch_size: _builtins.int = ...,
        batch_index: _builtins.int = ...,
        batch_id: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["batch_id", b"batch_id", "batch_index", b"batch_index", "batch_size", b"batch_size", "otp_parameters", b"otp_parameters", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MigrationPayload: _TypeAlias = MigrationPayload  # noqa: Y015
